# Generated by Django 4.2.3 on 2023-08-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("COURSE_NAME", models.CharField(max_length=255)),
                ("year_of_study", models.IntegerField()),
                ("semester", models.IntegerField()),
            ],
        ),
    ]
