# Generated by Django 4.2.3 on 2023-08-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Facilities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("halls_of_residence", models.CharField(max_length=100)),
                ("cafeterias", models.CharField(max_length=100)),
                ("Lecture_rooms", models.CharField(max_length=100)),
                ("sports_equipment", models.CharField(max_length=100)),
                ("facility_availability", models.CharField(max_length=100)),
                ("equipment_access", models.CharField(max_length=100)),
                ("usage_frequency", models.CharField(max_length=100)),
                ("Labs_usage", models.CharField(max_length=100)),
                ("facility_up_to_date", models.CharField(max_length=100)),
                ("school_resources_availability", models.CharField(max_length=100)),
                ("library_usage", models.CharField(max_length=100)),
                ("coursework_improvement", models.CharField(max_length=5000)),
                ("sports_equipment_adequacy", models.CharField(max_length=100)),
                ("sports_facilities_wish", models.CharField(max_length=5000)),
                ("equipment_wish", models.CharField(max_length=5000)),
                ("experience_improvement", models.CharField(max_length=5000)),
                ("overall_satisfaction", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "facilities",
            },
        ),
    ]
