# Generated by Django 4.2.3 on 2023-08-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        #migrations.AddField(
            #model_name="course",
            #name="CH",
            #field=models.CharField(default="", max_length=10),
        #),
        #migrations.AddField(
            #model_name="course",
            #name="CODE",
            #field=models.CharField(max_length=10, null=True),
        #),
        migrations.AddField(
            model_name="course",
            name="CU",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="LH",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="Origin",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="PH",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="Remark",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="TH",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="Type",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="program",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="COURSE_NAME",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="semester",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="year_of_study",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterModelTable(
            name="course",
            table="course_info",
        ),
    ]
