# Generated by Django 4.2.3 on 2023-08-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0002_course_ch_course_code_course_cu_course_lh_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="CODE",
        ),
        migrations.RemoveField(
            model_name="course",
            name="Origin",
        ),
        migrations.RemoveField(
            model_name="course",
            name="Remark",
        ),
        migrations.AddField(
            model_name="course",
            name="Remerk",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="CH",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="COURSE_NAME",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="course",
            name="program",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="code",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
