# Generated by Django 4.2.3 on 2023-08-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0004_courseinfo_delete_course"),
    ]

    operations = [
        migrations.CreateModel(
            name="YearOfStudy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year_of_study", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "course_info",
                "managed": False,
            },
        ),
    ]
